package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// XComorbidity represents a row from 'public.x_comorbidities'.
type XComorbidity struct {
	ID                                int             `json:"id"`                                  // id
	EncounterID                       sql.NullInt64   `json:"encounter_id"`                        // encounter_id
	Note                              sql.NullString  `json:"note"`                                // note
	ChronicCardiac                    sql.NullInt64   `json:"chronic_cardiac"`                     // chronic_cardiac
	Hypertension                      sql.NullInt64   `json:"hypertension"`                        // hypertension
	ChronicPulmonary                  sql.NullInt64   `json:"chronic_pulmonary"`                   // chronic_pulmonary
	Asthma                            sql.NullInt64   `json:"asthma"`                              // asthma
	ChronicKidney                     sql.NullInt64   `json:"chronic_kidney"`                      // chronic_kidney
	ChronicLiver                      sql.NullInt64   `json:"chronic_liver"`                       // chronic_liver
	ChronicNeurological               sql.NullInt64   `json:"chronic_neurological"`                // chronic_neurological
	Alcohol                           sql.NullInt64   `json:"alcohol"`                             // alcohol
	SexuallyTransmitted               sql.NullInt64   `json:"sexually_transmitted"`                // sexually_transmitted
	Diabetes                          sql.NullInt64   `json:"diabetes"`                            // diabetes
	Smoking                           sql.NullInt64   `json:"smoking"`                             // smoking
	TuberculosisActive                sql.NullInt64   `json:"tuberculosis_active"`                 // tuberculosis_active
	TuberculosisPrevious              sql.NullInt64   `json:"tuberculosis_previous"`               // tuberculosis_previous
	Asplenia                          sql.NullInt64   `json:"asplenia"`                            // asplenia
	MalignantNeoplasm                 sql.NullInt64   `json:"malignant_neoplasm"`                  // malignant_neoplasm
	NeoplasmPresent                   sql.NullInt64   `json:"neoplasm_present"`                    // neoplasm_present
	Immunosuppressants                sql.NullInt64   `json:"immunosuppressants"`                  // immunosuppressants
	ImmunosuppressantsSpecify         sql.NullString  `json:"immunosuppressants_specify"`          // immunosuppressants_specify
	ImmunosuppressiveCondition        sql.NullInt64   `json:"immunosuppressive_condition"`         // immunosuppressive_condition
	ImmunosuppressiveConditionSpecify sql.NullString  `json:"immunosuppressive_condition_specify"` // immunosuppressive_condition_specify
	NGonorrhoeae                      sql.NullInt64   `json:"n_gonorrhoeae"`                       // n_gonorrhoeae
	Syphilis                          sql.NullInt64   `json:"syphilis"`                            // syphilis
	Hsv                               sql.NullInt64   `json:"hsv"`                                 // hsv
	Chlamydia                         sql.NullInt64   `json:"chlamydia"`                           // chlamydia
	SexuallyOthers                    sql.NullString  `json:"sexually_others"`                     // sexually_others
	Hiv                               sql.NullInt64   `json:"hiv"`                                 // hiv
	ArtRegiment                       sql.NullString  `json:"art_regiment"`                        // art_regiment
	Cd4                               sql.NullFloat64 `json:"cd4"`                                 // cd4
	ViralLoad                         sql.NullFloat64 `json:"viral_load"`                          // viral_load
	EnterBy                           sql.NullInt64   `json:"enter_by"`                            // enter_by
	EnterOn                           sql.NullTime    `json:"enter_on"`                            // enter_on
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [XComorbidity] exists in the database.
func (xc *XComorbidity) Exists() bool {
	return xc._exists
}

// Deleted returns true when the [XComorbidity] has been marked for deletion
// from the database.
func (xc *XComorbidity) Deleted() bool {
	return xc._deleted
}

// Insert inserts the [XComorbidity] to the database.
func (xc *XComorbidity) Insert(ctx context.Context, db DB) error {
	switch {
	case xc._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case xc._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.x_comorbidities (` +
		`encounter_id, note, chronic_cardiac, hypertension, chronic_pulmonary, asthma, chronic_kidney, chronic_liver, chronic_neurological, alcohol, sexually_transmitted, diabetes, smoking, tuberculosis_active, tuberculosis_previous, asplenia, malignant_neoplasm, neoplasm_present, immunosuppressants, immunosuppressants_specify, immunosuppressive_condition, immunosuppressive_condition_specify, n_gonorrhoeae, syphilis, hsv, chlamydia, sexually_others, hiv, art_regiment, cd4, viral_load, enter_by, enter_on` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33` +
		`) RETURNING id`
	// run
	logf(sqlstr, xc.EncounterID, xc.Note, xc.ChronicCardiac, xc.Hypertension, xc.ChronicPulmonary, xc.Asthma, xc.ChronicKidney, xc.ChronicLiver, xc.ChronicNeurological, xc.Alcohol, xc.SexuallyTransmitted, xc.Diabetes, xc.Smoking, xc.TuberculosisActive, xc.TuberculosisPrevious, xc.Asplenia, xc.MalignantNeoplasm, xc.NeoplasmPresent, xc.Immunosuppressants, xc.ImmunosuppressantsSpecify, xc.ImmunosuppressiveCondition, xc.ImmunosuppressiveConditionSpecify, xc.NGonorrhoeae, xc.Syphilis, xc.Hsv, xc.Chlamydia, xc.SexuallyOthers, xc.Hiv, xc.ArtRegiment, xc.Cd4, xc.ViralLoad, xc.EnterBy, xc.EnterOn)
	if err := db.QueryRowContext(ctx, sqlstr, xc.EncounterID, xc.Note, xc.ChronicCardiac, xc.Hypertension, xc.ChronicPulmonary, xc.Asthma, xc.ChronicKidney, xc.ChronicLiver, xc.ChronicNeurological, xc.Alcohol, xc.SexuallyTransmitted, xc.Diabetes, xc.Smoking, xc.TuberculosisActive, xc.TuberculosisPrevious, xc.Asplenia, xc.MalignantNeoplasm, xc.NeoplasmPresent, xc.Immunosuppressants, xc.ImmunosuppressantsSpecify, xc.ImmunosuppressiveCondition, xc.ImmunosuppressiveConditionSpecify, xc.NGonorrhoeae, xc.Syphilis, xc.Hsv, xc.Chlamydia, xc.SexuallyOthers, xc.Hiv, xc.ArtRegiment, xc.Cd4, xc.ViralLoad, xc.EnterBy, xc.EnterOn).Scan(&xc.ID); err != nil {
		return logerror(err)
	}
	// set exists
	xc._exists = true
	return nil
}

// Update updates a [XComorbidity] in the database.
func (xc *XComorbidity) Update(ctx context.Context, db DB) error {
	switch {
	case !xc._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case xc._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.x_comorbidities SET ` +
		`encounter_id = $1, note = $2, chronic_cardiac = $3, hypertension = $4, chronic_pulmonary = $5, asthma = $6, chronic_kidney = $7, chronic_liver = $8, chronic_neurological = $9, alcohol = $10, sexually_transmitted = $11, diabetes = $12, smoking = $13, tuberculosis_active = $14, tuberculosis_previous = $15, asplenia = $16, malignant_neoplasm = $17, neoplasm_present = $18, immunosuppressants = $19, immunosuppressants_specify = $20, immunosuppressive_condition = $21, immunosuppressive_condition_specify = $22, n_gonorrhoeae = $23, syphilis = $24, hsv = $25, chlamydia = $26, sexually_others = $27, hiv = $28, art_regiment = $29, cd4 = $30, viral_load = $31, enter_by = $32, enter_on = $33 ` +
		`WHERE id = $34`
	// run
	logf(sqlstr, xc.EncounterID, xc.Note, xc.ChronicCardiac, xc.Hypertension, xc.ChronicPulmonary, xc.Asthma, xc.ChronicKidney, xc.ChronicLiver, xc.ChronicNeurological, xc.Alcohol, xc.SexuallyTransmitted, xc.Diabetes, xc.Smoking, xc.TuberculosisActive, xc.TuberculosisPrevious, xc.Asplenia, xc.MalignantNeoplasm, xc.NeoplasmPresent, xc.Immunosuppressants, xc.ImmunosuppressantsSpecify, xc.ImmunosuppressiveCondition, xc.ImmunosuppressiveConditionSpecify, xc.NGonorrhoeae, xc.Syphilis, xc.Hsv, xc.Chlamydia, xc.SexuallyOthers, xc.Hiv, xc.ArtRegiment, xc.Cd4, xc.ViralLoad, xc.EnterBy, xc.EnterOn, xc.ID)
	if _, err := db.ExecContext(ctx, sqlstr, xc.EncounterID, xc.Note, xc.ChronicCardiac, xc.Hypertension, xc.ChronicPulmonary, xc.Asthma, xc.ChronicKidney, xc.ChronicLiver, xc.ChronicNeurological, xc.Alcohol, xc.SexuallyTransmitted, xc.Diabetes, xc.Smoking, xc.TuberculosisActive, xc.TuberculosisPrevious, xc.Asplenia, xc.MalignantNeoplasm, xc.NeoplasmPresent, xc.Immunosuppressants, xc.ImmunosuppressantsSpecify, xc.ImmunosuppressiveCondition, xc.ImmunosuppressiveConditionSpecify, xc.NGonorrhoeae, xc.Syphilis, xc.Hsv, xc.Chlamydia, xc.SexuallyOthers, xc.Hiv, xc.ArtRegiment, xc.Cd4, xc.ViralLoad, xc.EnterBy, xc.EnterOn, xc.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [XComorbidity] to the database.
func (xc *XComorbidity) Save(ctx context.Context, db DB) error {
	if xc.Exists() {
		return xc.Update(ctx, db)
	}
	return xc.Insert(ctx, db)
}

// Upsert performs an upsert for [XComorbidity].
func (xc *XComorbidity) Upsert(ctx context.Context, db DB) error {
	switch {
	case xc._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.x_comorbidities (` +
		`id, encounter_id, note, chronic_cardiac, hypertension, chronic_pulmonary, asthma, chronic_kidney, chronic_liver, chronic_neurological, alcohol, sexually_transmitted, diabetes, smoking, tuberculosis_active, tuberculosis_previous, asplenia, malignant_neoplasm, neoplasm_present, immunosuppressants, immunosuppressants_specify, immunosuppressive_condition, immunosuppressive_condition_specify, n_gonorrhoeae, syphilis, hsv, chlamydia, sexually_others, hiv, art_regiment, cd4, viral_load, enter_by, enter_on` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`encounter_id = EXCLUDED.encounter_id, note = EXCLUDED.note, chronic_cardiac = EXCLUDED.chronic_cardiac, hypertension = EXCLUDED.hypertension, chronic_pulmonary = EXCLUDED.chronic_pulmonary, asthma = EXCLUDED.asthma, chronic_kidney = EXCLUDED.chronic_kidney, chronic_liver = EXCLUDED.chronic_liver, chronic_neurological = EXCLUDED.chronic_neurological, alcohol = EXCLUDED.alcohol, sexually_transmitted = EXCLUDED.sexually_transmitted, diabetes = EXCLUDED.diabetes, smoking = EXCLUDED.smoking, tuberculosis_active = EXCLUDED.tuberculosis_active, tuberculosis_previous = EXCLUDED.tuberculosis_previous, asplenia = EXCLUDED.asplenia, malignant_neoplasm = EXCLUDED.malignant_neoplasm, neoplasm_present = EXCLUDED.neoplasm_present, immunosuppressants = EXCLUDED.immunosuppressants, immunosuppressants_specify = EXCLUDED.immunosuppressants_specify, immunosuppressive_condition = EXCLUDED.immunosuppressive_condition, immunosuppressive_condition_specify = EXCLUDED.immunosuppressive_condition_specify, n_gonorrhoeae = EXCLUDED.n_gonorrhoeae, syphilis = EXCLUDED.syphilis, hsv = EXCLUDED.hsv, chlamydia = EXCLUDED.chlamydia, sexually_others = EXCLUDED.sexually_others, hiv = EXCLUDED.hiv, art_regiment = EXCLUDED.art_regiment, cd4 = EXCLUDED.cd4, viral_load = EXCLUDED.viral_load, enter_by = EXCLUDED.enter_by, enter_on = EXCLUDED.enter_on `
	// run
	logf(sqlstr, xc.ID, xc.EncounterID, xc.Note, xc.ChronicCardiac, xc.Hypertension, xc.ChronicPulmonary, xc.Asthma, xc.ChronicKidney, xc.ChronicLiver, xc.ChronicNeurological, xc.Alcohol, xc.SexuallyTransmitted, xc.Diabetes, xc.Smoking, xc.TuberculosisActive, xc.TuberculosisPrevious, xc.Asplenia, xc.MalignantNeoplasm, xc.NeoplasmPresent, xc.Immunosuppressants, xc.ImmunosuppressantsSpecify, xc.ImmunosuppressiveCondition, xc.ImmunosuppressiveConditionSpecify, xc.NGonorrhoeae, xc.Syphilis, xc.Hsv, xc.Chlamydia, xc.SexuallyOthers, xc.Hiv, xc.ArtRegiment, xc.Cd4, xc.ViralLoad, xc.EnterBy, xc.EnterOn)
	if _, err := db.ExecContext(ctx, sqlstr, xc.ID, xc.EncounterID, xc.Note, xc.ChronicCardiac, xc.Hypertension, xc.ChronicPulmonary, xc.Asthma, xc.ChronicKidney, xc.ChronicLiver, xc.ChronicNeurological, xc.Alcohol, xc.SexuallyTransmitted, xc.Diabetes, xc.Smoking, xc.TuberculosisActive, xc.TuberculosisPrevious, xc.Asplenia, xc.MalignantNeoplasm, xc.NeoplasmPresent, xc.Immunosuppressants, xc.ImmunosuppressantsSpecify, xc.ImmunosuppressiveCondition, xc.ImmunosuppressiveConditionSpecify, xc.NGonorrhoeae, xc.Syphilis, xc.Hsv, xc.Chlamydia, xc.SexuallyOthers, xc.Hiv, xc.ArtRegiment, xc.Cd4, xc.ViralLoad, xc.EnterBy, xc.EnterOn); err != nil {
		return logerror(err)
	}
	// set exists
	xc._exists = true
	return nil
}

// Delete deletes the [XComorbidity] from the database.
func (xc *XComorbidity) Delete(ctx context.Context, db DB) error {
	switch {
	case !xc._exists: // doesn't exist
		return nil
	case xc._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.x_comorbidities ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, xc.ID)
	if _, err := db.ExecContext(ctx, sqlstr, xc.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	xc._deleted = true
	return nil
}

// XComorbidityByID retrieves a row from 'public.x_comorbidities' as a [XComorbidity].
//
// Generated from index 'comorbidities_pkey'.
func XComorbidityByID(ctx context.Context, db DB, id int) (*XComorbidity, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, encounter_id, note, chronic_cardiac, hypertension, chronic_pulmonary, asthma, chronic_kidney, chronic_liver, chronic_neurological, alcohol, sexually_transmitted, diabetes, smoking, tuberculosis_active, tuberculosis_previous, asplenia, malignant_neoplasm, neoplasm_present, immunosuppressants, immunosuppressants_specify, immunosuppressive_condition, immunosuppressive_condition_specify, n_gonorrhoeae, syphilis, hsv, chlamydia, sexually_others, hiv, art_regiment, cd4, viral_load, enter_by, enter_on ` +
		`FROM public.x_comorbidities ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	xc := XComorbidity{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&xc.ID, &xc.EncounterID, &xc.Note, &xc.ChronicCardiac, &xc.Hypertension, &xc.ChronicPulmonary, &xc.Asthma, &xc.ChronicKidney, &xc.ChronicLiver, &xc.ChronicNeurological, &xc.Alcohol, &xc.SexuallyTransmitted, &xc.Diabetes, &xc.Smoking, &xc.TuberculosisActive, &xc.TuberculosisPrevious, &xc.Asplenia, &xc.MalignantNeoplasm, &xc.NeoplasmPresent, &xc.Immunosuppressants, &xc.ImmunosuppressantsSpecify, &xc.ImmunosuppressiveCondition, &xc.ImmunosuppressiveConditionSpecify, &xc.NGonorrhoeae, &xc.Syphilis, &xc.Hsv, &xc.Chlamydia, &xc.SexuallyOthers, &xc.Hiv, &xc.ArtRegiment, &xc.Cd4, &xc.ViralLoad, &xc.EnterBy, &xc.EnterOn); err != nil {
		return nil, logerror(err)
	}
	return &xc, nil
}
